### ISSUE TITLE
Different behavior between `calculate(':where')` and `calculate(':is')`

### ISSUE THREAD

**Issue by ybiquitous** [bramus/specificity#12]
Hello. I notice the behavior of `calculate()` is different between `:where` and `:is` (without a selector list).

- `calculate(':where')` returns `{ a: 0, b: 0, c: 0 }`
- `calculate(':is')` throws `Uncaught TypeError`

Is this difference intentional?

See the reproduction below:

## Reproduction

1. Run the latest version via `npm i @bramus/specificity@2.1.0`.
2. Run Node.js REPL as below:

```console
$ node
Welcome to Node.js v18.1.0.
Type ".help" for more information.
> { default: S } = await import('@bramus/specificity')
[Module: null prototype] { default: [class Dn] }
> S.calculate(':where')
[
  Dn {
    value: { a: 0, b: 0, c: 0 },
    selector: { type: 'Selector', loc: null, children: [D] }
  }
]
> S.calculate(':is')
Uncaught TypeError: Cannot read properties of null (reading 'first')
    at D.<anonymous> (file:///Users/koba/tmp/foo/node_modules/@bramus/specificity/dist/index.js:6:6717)
    at D.forEach (file:///Users/koba/tmp/foo/node_modules/@bramus/specificity/dist/index.js:2:12977)
    at An (file:///Users/koba/tmp/foo/node_modules/@bramus/specificity/dist/index.js:6:6432)
    at D.<anonymous> (file:///Users/koba/tmp/foo/node_modules/@bramus/specificity/dist/index.js:6:7978)
    at D.forEach (file:///Users/koba/tmp/foo/node_modules/@bramus/specificity/dist/index.js:2:12977)
    at yt (file:///Users/koba/tmp/foo/node_modules/@bramus/specificity/dist/index.js:6:7960)
    at Function.calculate (file:///Users/koba/tmp/foo/node_modules/@bramus/specificity/dist/index.js:6:9121)
```

**Comment by bramus** [comment]
I’ve experimented with this a while ago and yes this is a bug.

Using `css-tree`’s `parse` directly to parse `:where`, `:is`, `:matches` works fine.

```js
import { parse } from "https://cdn.skypack.dev/css-tree@2.1.0";

const tryParse = (source) => {
	try {
		const parsed = parse(source, {
			context: 'selectorList',
		});
		console.log(parsed);
	} catch (e) {
		console.error(e);
	}
}
tryParse(':where'); // Object: { type: "SelectorList", children: …}
tryParse(':is'); // Object: { type: "SelectorList", children: …}
tryParse(':matches'); // Object: { type: "SelectorList", children: …}
```

Using `@bramus/specificity` to parse `:where`, `:is`, `:matches` does not.

```js
import Specificty from "https://cdn.skypack.dev/@bramus/specificity@2.1.0";

const trySpecificity = (source) => {
	try {
		const specificity = Specificty.calculate(source);
		console.log(specificity.toString());
	} catch (e) {
		console.error(e);
	}
}
trySpecificity(':where'); // (0,0,0)
trySpecificity(':is'); // Error: Cannot read properties of null (reading 'first')
trySpecificity(':matches'); // Error: Cannot read properties of null (reading 'first')
```

Demo page: https://codepen.io/bramus/details/MWVgWJB/91e31434e1e04bde9299a20d431a4f13 _(output shown in the console)_
